config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'

  # Article Routes
  resources :articles # -> gives all routes for articles resource
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # Category Routes
  resources :categories, except: [:destroy]
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: {minimum: 6, maximum: 100 }
  validates :description, presence: true, length: {minimum: 10, maximum: 300 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category 
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 25}
  validates_uniqueness_of :name
  has_many :article_categories
  has_many :articles, through: :article_categories
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles
  validates :username, presence: true, uniqueness: {case_sensitive: false }, length: {minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }, length: { maximum: 105 }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # adding methods here allows for every page of the application to have access to these methods

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end
end

app/controllers/articles_controller.rb
# frozen_string_literal: true
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy] #-> performs this method before anything else is done.
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  #show one
  def show
      # byebug # -> pauses web server, can be used to see params for the route
     
  end

  # show all
  def index
      # instance variable to make it available in views
      @articles = Article.paginate(page: params[:page], per_page: 3)
  end


  def new
      @article = Article.new
  end

  def edit
     
  end
  def create
      @article = Article.new(article_params)
      @article.user = current_user
      if @article.save
          flash[:notice] = "Article was created successfully."
          redirect_to @article
      else  
          render 'new' # render the new form if article save fails
      end
  end

  def update
     if @article.update(article_params)
      flash[:notice] = "Article was updated successfully."
      redirect_to @article
     else
      render 'edit'
     end
  end

  def destroy
      @article.destroy
      redirect_to articles_path # articles_path -> redirects to /articles 
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
      params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin? ##check if current user is an admin.
      flash[:alert] = "You can only edit or delete your own article"
      redirect_to @article
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :require_admin, except: [:index, :show]

  def index
    @categories = Category.order(:name).paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:notice] = 'Category was successfully created'
      redirect_to @category
    else
      render 'new'
    end
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page: 3)
  end

  def edit 
    @category = Category.find(params[:id])
  end

  def update 
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category was updated successfully."
      redirect_to @category
    else
      render 'edit'
    end
  end

  private

  def category_params
    # whitelisting params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = 'admin access only'
      redirect_to categories_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    redirect_to articles_path if logged_in?
  end

  def about
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
      redirect_to user
    else
      flash.now[:alert] = "There was something wrong with your login details"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:new, :show, :update]
  before_action :require_same_user, only: [:edit, :update]

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 3)
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 3)
    @articles
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the Travel Blog #{@user.username}, you have successfully signed up"
      redirect_to articles_path
    else 
      render 'new'
    end
  end

  def edit
    
  end

 

  def update
    
    if @user.update(user_params)
      flash[:notice] = "Profile was updated successfully."
      redirect_to @user
    else
      render 'edit'
    end
  end


  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account and all associated articles successfully deleted"
    redirect_to articles_path
  end

  
  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own account"
      redirect_to @user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = {size: 80})
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class:"rounded shadow mx-auto d-block")
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class=="container">
  <% @articles.each do |article| %>
  <div class="row justify-content-md-center">
    <div class="col-4 mt-4">
    <div class="card text-center shadow mb-5 bg-white rounded">
      <div class="card-header font-italic">
        <% if article.user %>
          By <em><%= link_to article.user.username.capitalize(), user_path(article.user) %></em>
        <%else%>
          <em>Author Anonymous</em>  
        <% end %>
        <% if article.categories.any? %>
        <%# loops through categories array and renders a partial for each %>
          <div class="my-2">
            <%= render article.categories %> 
          </div> 
        <%else%>
          <div>No category assigned</div>
      <% end %>
      </div>
      <div class="card-body">
        <h5 class="card-title"><%= link_to article.title , article_path(article),class: "text-success"%></h5>
        <p class="card-text"><%= truncate(article.description,length: 100)%></p>
        <%= link_to "View" , article_path(article),class: "btn btn-outline-success"%>
         <% if logged_in? && (article.user == current_user || current_user.admin?) %>
          <%= link_to 'Edit', edit_article_path(article), class: "btn btn-outline-primary" %>
          <%= button_to 'Delete', article_path(article), class: "btn btn-outline-danger mt-2", method: :delete, data: { confirm: "Are you sure?" } %>
        <% end %>
      </div>
      <div class="card-footer  text-muted">
        <small>Created <%= time_ago_in_words(article.created_at)%>, ago</small>
        <small>Update <%= time_ago_in_words(article.updated_at)%>, ago</small>
      </div>
    </div>
    </div>
  </div>
  <% end %>
</div>

app/views/articles/_forms.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
  <%= render 'shared/errors', obj: @article%>

  <%= form_with(model: @article, local: true)  do |f| %>
        <div class="form-group row">
          <strong><%= f.label :title, class: "col-2 col-form-label text-dark" %></strong>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
          </div>
        </div>
        <div class="form-group row">
          <strong><%= f.label :description, class: "col-2 col-form-label text-dark" %></strong>
          <div class="col-10"> 
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
          </div>
        </div>
        <div class="form-group row">
          <strong><%= f.label :category, class: "col-2 col-form-label text-dark" %></strong>
          <div class="col-10">
             <%= f.collection_select :category_ids, Category.order(:name), :id, :name,
             {prompt: "Select a Category Below (can be empty) CMD+C to select multiple"}, {multiple: true, size: 3, class: 'form-select form-select-md mb-3 shadow rounded'} %> 
          </div>
        </div>

        <div class="form-group mt-4 justify-content-center">
          <%= f.submit class: "btn btn-outline-success btn-lg" %>
        </div>
      <% end %>
      <form>
    </div>
    <div class="my-3">
      <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info" %>
  </div>
 </div>
</div>

app/views/articles/edit.html.erb
<h1>Edit Article: <em><%= @article.title %></em></h1>

<%= render 'forms'%>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Articles Listing Page</h1>
<div class="apple_pagination">
  <%= will_paginate @articles, :container => false %>
</div>


<%= render 'article'%>


<div class="apple_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>
  <%# link_to won't work due to line 10 within application.html.erb file being commented out. so I used button_to until I can find a fix. %>
   

app/views/articles/new.html.erb
<h1>Create a New Article</h1>

<%= render 'forms' %>

app/views/articles/show.html.erb
<div class="container text-center">
<h1>Article Details</h1>
  <div class="card mt-4 mx-5 py-4">
  <div class="card-body">
    <div class="card header mx-3 font-italic"> 
      <%= @article.user.username if @article.user %>
      <%= link_to gravatar_for(@article.user), user_path(@article.user)%>
      <% if @article.categories.any? %>
        <%# loops through categories array and renders a partial for each %>
        <div class="my-3">
          <%= render @article.categories %> 
        </div> 
      <% end %>
    </div>
    <h5 class="card-title"><strong>Title: </strong><%= @article.title %></h5>
    <p class="card-text"><%= @article.description %></p>
     <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
      <%= link_to 'Edit', edit_article_path(@article),class: "btn btn-primary" %>
      <%= link_to 'Delete', article_path(@article), class:"btn btn-outline-danger", method: :delete, data: { confirm: "Are you sure?" }%>
     <% end %>
    <%= link_to 'Return to articles listing', articles_path, class: "btn btn-warning"%>
  </div>
  </div>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "bg-info badge badge-pill text-white mx-2" %>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>
<%= form_with(model: @category, class: "shadow p-3 mb-3 bg-info rounded", local: true)  do |f| %>
     <div class="form-group row">
       <strong><%= f.label :name, "Category Name:", class: "col-2 col-form-label text-dark" %></strong>
        <div class="col-10">
          <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter Name Here " %>
        </div>
        
      </div>

      <div class="form-group mt-4 justify-content-center">
        <%= f.submit class: "btn btn-outline-success btn-lg" %>
      </div>

<% end %>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4">Edit Category Name</h1>
<div class="container">
  <div class="row justify-content-center">
  <div class="col-10">
    <%= render 'form'%>
    </div>
   <div class="my-3">
      <%= link_to '[ Cancel and return to category ]', category_path(@category), class: "text-info" %>
  </div>
 </div>
</div>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Categories</h1>

<div class="apple_pagination">
  <%= will_paginate @categories, :container => false %>
</div>

<div class=="container">
  <% @categories.each do |category| %>
    <div class="row justify-content-md-center">
      <div class="col-3 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-body">
            <h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-success"%></h5>
            <p class="card-text"><%= pluralize(category.articles.count, "category") %></p>
          </div>
          <div class="card-footer  text-muted">
            <small>Created <%= time_ago_in_words(category.created_at)%>, ago</small>
            <small>Update <%= time_ago_in_words(category.updated_at)%>, ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<div class="apple_pagination mb-4">
  <%= will_paginate @categories, :container => false %>
</div>

</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4">Create a new Category</h1>
<div class="container">
  <div class="row justify-content-center">
  <div class="col-10">
    <%= render 'shared/errors', obj: @category %>

    <%= form_with(model: @category, class: "shadow p-3 mb-3 bg-info rounded", local: true)  do |f| %>
     <div class="form-group row">
       <strong><%= f.label :name, "Category Name:", class: "col-2 col-form-label text-dark" %></strong>
        <div class="col-10">
          <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter Name Here " %>
        </div>
      </div>

      <div class="form-group mt-4 justify-content-center">
        <%= f.submit class: "btn btn-outline-success btn-lg" %>
      </div>

    <% end %>
    </div>
   <div class="my-3">
      <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info" %>
  </div>
 </div>
</div>

app/views/categories/show.html.erb
<h1 class="text-center mt-4"> Category: <em><%= @category.name %></em></h1>

<% if logged_in? && current_user.admin? %>
  <div class="text-center mb-4">
  <%= link_to "Edit Category Name", edit_category_path(@category), class:"btn btn-outline-info" %>
  </div>
<% end %>

<h3 class="text-center my-2"> Articles </h3>

<div class="apple_pagination ">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article' %>

<div class="apple_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
    <div class="container text-center">
      <small>Copyright &copy; <%= link_to "Mysta3", "https://github.com/" ,class: "text-white" %></small>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<%# Place here to let all views have access to these flash messages. %>
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
    </div>
  <% end %> 
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Travel Blog", root_path, class: "navbar-brand", id: "logo" %>
    <div class="navbar navbar-expand" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
         <%= link_to "Articles", articles_path, class: "nav-link"%>
        </li>

        <% if logged_in? && current_user.admin? %>
        <li class="nav-item active">
          <%= link_to "Categories" , categories_path, class: "nav-link"%>
        </li>
        <li class="nav-item text-success">
          <%= link_to'Create new Category', new_category_path, class:"text-white nav-link mx-2"%>
        </li>
      <% end %>

    <li class="nav-item">
        <%= link_to "Bloggers", users_path, class: "nav-link" %>
      </li>
      <% if logged_in? && current_user %>
      <li class="nav-item text-success">
        <%= link_to 'Create new Article', new_article_path, class:"text-white nav-link mx-2"%>
      </li>
      <li class="nav-item text-info mx-4 my-0">
        <%= "(Admin)" if current_user.admin? %><%= link_to current_user.username, user_path(current_user), class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= button_to 'Logout', logout_path , class: "nav-link btn btn-outline-warning", method: :delete %>
      </li>
      <%= button_to "Delete profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { confirm: "Are you sure?" } %>
      <% else %>
      <li class="nav-item">
        <%= link_to 'Log in', login_path, class: "nav-link" %>
      </li>
      <% end %>

      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Travel Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- cross-site request forgery protection -->
    <%= csrf_meta_tags %> 
    <!-- #protects against unknown scripts -->
    <%= csp_meta_tag %> 

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

 <%
=begin%>
 <%= #javascript_pack_tag 'application.js', 'data-turbolinks-track': 'reload' %>  
<%
=end%>

  </head>

  <body class="d-flex flex-column">
   <%= render 'layouts/navigation'%>
    <div id="page-content">
      <%# render flash messages here %>
      <%= render 'layouts/messages' %> 
      <%= yield %>
    </div>


  <%= render 'layouts/footer'%>  
  
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <div class="jumbotron text-center text-white mt-5">
    <h1 class="display-2 my-4">About</h1>
    <%= link_to 'Go to Articles', articles_path , class:"text-monospace btn btn-light mx-3"%> 
    <%= link_to 'Go to Home Page', root_path , class:"text-monospace btn btn-dark"%> 
  </div>
  <div id="about-description" class="bg-white mt-5 text-dark">
    <div class="container-fluid">
      <h3 class="text-center"><u>PURPOSE</u></h3>
      <P>Built for educational purposes. But can be used to create topics and blogs</P>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p> 

      <h3 class="text-center my-4"><u>WHY</u></h3>
      <P>Built for educational purposes. This app was built using Ruby on Rails and for understanding different design patterns as well as how ActiveRecord works within the Rails language.</P>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p> 
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container" id="home-container">
  <div class="jumbotron text-center text-white mt-5" id="jumbotron_image">
    <h1 id="homepage_title" class="display-2 my-4">Welcome To A World Of Wonder</h1>
    <div class="hero-description">
      <p class=" lead text-dark ">A Site For Travelers Of All Kinds To Be Able To Read & Write About Places They Have Been.</p>
      <p class="fst-italic text-dark"><strong>JOIN IN ON THE FUN BY SIGNING UP OR LOGGING IN!</strong></p>
        <%= link_to "Sign up!", signup_path, class: "btn btn-success shadow btn-lg mb-2" %>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading"> The following errors prevented the <%= obj.class.name.downcase %> from being saved </h4>
    <ul>
      <% obj.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
    <%= render 'shared/errors', obj: @user%>

    <%= form_with(model: @user, local: true)  do |f| %>
        <div class="form-group row">
          <strong><%= f.label :username, class: "col-2 col-form-label text-dark" %></strong>
          <div class="col-10">
            <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter a Username" %>
          </div>
        </div>
        <div class="form-group row">
          <strong><%= f.label :email, class: "col-2 col-form-label text-dark" %></strong>
          <div class="col-10"> 
            <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter Email" %>
          </div>
        </div>
        <div class="form-group row">
          <strong><%= f.label :password, class: "col-2 col-form-label text-dark" %></strong>
          <div class="col-10"> 
            <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Enter Password" %>
          </div>
        </div>

        <div class="form-group mt-4 justify-content-center">
          <%= f.submit(@user.new_record? ? "Sign Up" : "Update Account" , class: "btn btn-outline-success btn-lg" )%>
        </div>
      <% end %>
      <form>
    </div>
    <div class="my-3">
      <%= link_to '[ Cancel and return to articles listing ]', articles_path %>
  </div>
 </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit Your Profile </h1>

<%= render 'form'%>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Travel Bloggers</h1>
<div class="apple_pagination">
  <%= will_paginate @users, :container => false %>
</div>

<div class=="container">
  <% @users.each do |user| %>
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
    <div class="card text-center shadow mb-5 bg-white rounded">
      <div class="card-header font-italic">
       <%= link_to user.username, user_path(user) %>
      </div>
      <div class="card-body">
        <h5 class="card-title"><%= link_to  gravatar_for(user, size: 150),user %></h5>
        <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
        <%= link_to "View Profile" , user ,class: "btn btn-outline-success"%>
        <% if logged_in? %> 
          <% if user == current_user %>
            <%= link_to 'Edit Profile', edit_user_path(user), class: "btn btn-outline-info" %>
          <% end %>
          <% if current_user.admin? %>
                <%= link_to "Delete user", user_path(user), class: "btn btn-outline-danger", method: :delete,
                data: {confirm: "Are you sure you want to delete the user account and all associated articles?"} %>
          <% end %>
        <% end %>
      </div>
      <div class="card-footer  text-muted">
        <small>Joined <%= time_ago_in_words(user.created_at)%>, ago</small>
      </div>
    </div>
    </div>
  </div>
  <% end %>
</div>

<div class="apple_pagination mb-4">
  <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign Up For Travel Blog</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"> <em><%= @user.username %></em>'s Profile</h1>

<%= gravatar_for @user, size: 200 %>

<% if logged_in? && @user == current_user %>
  <div class="text-center mt-4">
  <%= link_to "Edit your profile", edit_user_path(@user), class:"btn btn-outline-info" %>
  </div>
<% end %>

<h3 class="text-center mt-4"> Articles </h3>
<div class="apple_pagination ">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article' %>

<div class="apple_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>